#!/bin/bash

sudo yum install -y docker
sudo groupadd docker
sudo usermod -aG docker $(whoami)
cd docker-jenkins
sudo systemctl start docker
sudo exec su -l $USER
docker build -t jenkins-xav .
docker run -d -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock \
-v $(pwd)/jobs:/var/jenkins_home/jobs:Z --name jenkins jenkins-xav
